-- ============================================================
-- DỮ LIỆU TRƯỜNG TIỂU HỌC DIỄN LIÊN
-- Sinh tự động từ data/truong-dien-lien.json — đừng sửa tay.
-- ------------------------------------------------------------
-- 25 lớp · 35 giáo viên · 265 dòng phân công
-- Tổng 710 tiết/tuần
--
-- Chạy SAU db/khoi-tao.sql. Dán cả file vào SQL Editor, bấm Run.
-- Chạy lại nhiều lần cũng không sao, không tạo bản trùng.
-- ============================================================

-- ---------- 1. Điểm trường ----------
insert into diem_truong (truong_id, ten, co_phong_tin, thu_tu)
select t.id, 'Điểm trường Diễn Liên', true, 0 from truong t
where t.ma_truong = 'THDL'
  and not exists (select 1 from diem_truong d where d.truong_id = t.id and d.ten = 'Điểm trường Diễn Liên');

-- ---------- 2. Khung giờ: 8 buổi thật, số tiết riêng từng khối ----------
-- so_tiet_khoi đọc từ bản kết xuất SmartScheduler: khối 1-2 = 27 tiết,
-- khối 3 = 28, khối 4-5 = 30 — đúng chuẩn CT GDPT 2018.
insert into khung_gio (truong_id, thu, buoi, so_tiet, so_tiet_khoi, bat)
select t.id, v.thu::smallint, v.buoi::buoi_t, v.so_tiet::smallint, v.so_tiet_khoi::jsonb, v.bat
from (values
  (2,'S',4,'{"1":4,"2":4,"3":4,"4":4,"5":4}',true),
  (2,'C',3,'{"1":3,"2":3,"3":3,"4":3,"5":3}',true),
  (3,'S',4,'{"1":4,"2":4,"3":4,"4":4,"5":4}',true),
  (3,'C',3,'{"1":2,"2":2,"3":3,"4":3,"5":3}',true),
  (4,'S',4,'{"1":4,"2":4,"3":4,"4":4,"5":4}',true),
  (4,'C',3,'{"1":3,"2":3,"3":3,"4":3,"5":3}',false),
  (5,'S',4,'{"1":4,"2":4,"3":4,"4":4,"5":4}',true),
  (5,'C',3,'{"1":2,"2":2,"3":2,"4":3,"5":3}',true),
  (6,'S',5,'{"1":4,"2":4,"3":4,"4":5,"5":5}',true),
  (6,'C',3,'{"1":3,"2":3,"3":3,"4":3,"5":3}',false)
) as v(thu, buoi, so_tiet, so_tiet_khoi, bat)
join truong t on t.ma_truong = 'THDL'
on conflict (truong_id, thu, buoi) do update set
  so_tiet = excluded.so_tiet, so_tiet_khoi = excluded.so_tiet_khoi, bat = excluded.bat;

-- ---------- 3. Giáo viên ----------
-- ma_gv giữ nguyên mã trong dữ liệu vàng, nhờ đó chạy lại không trùng
-- và bốn cặp trùng tên gọi vẫn phân biệt được.
insert into giao_vien (truong_id, ma_gv, ho_ten, dinh_muc)
select t.id, v.ma_gv, v.ho_ten, v.dinh_muc::smallint
from (values
  ('gv_nguyen_thi_trinh','Nguyễn Thị Trinh',23),
  ('gv_cao_thi_minh_khue','Cao Thị Minh Khuê',23),
  ('gv_bui_thi_dung','Bùi Thị Dung',23),
  ('gv_hoang_thi_linh','Hoàng Thị Linh',23),
  ('gv_dang_thi_hue','Đặng Thị Huệ',23),
  ('gv_nguyen_thi_khanh','Nguyễn Thị Khánh',23),
  ('gv_cao_thi_hoe','Cao Thị Hòe',23),
  ('gv_truong_thi_phuong','Trương Thị Phương',23),
  ('gv_nguyen_thi_thoa','Nguyễn Thị Thoa',23),
  ('gv_nguyen_thi_tram','Nguyễn Thị Trầm',23),
  ('gv_dang_thi_dung','Đặng Thị Dung',23),
  ('gv_ho_thi_hang','Hồ Thị Hằng',23),
  ('gv_chu_thi_tham','Chu Thị Thắm',23),
  ('gv_nguyen_thi_lam','Nguyễn Thị Lam',23),
  ('gv_tang_thi_huong_giang','Tăng Thị Hương Giang',23),
  ('gv_nguyen_thi_oanh','Nguyễn Thị Oanh',23),
  ('gv_phan_thi_bien','Phan Thị Biên',23),
  ('gv_nguyen_thi_hong_thuy','Nguyễn Thị Hồng Thủy',23),
  ('gv_nguyen_thi_thuy','Nguyễn Thị Thùy',23),
  ('gv_nguyen_thi_hoa','Nguyễn Thị Hòa',23),
  ('gv_bui_duc_hong','Bùi Đức Hồng',23),
  ('gv_truong_thi_hong_ngoc','Trương Thị Hồng Ngọc',23),
  ('gv_cao_thi_thanh_huong','Cao Thị Thanh Hương',23),
  ('gv_nguyen_thi_hoan_my','Nguyễn Thị Hoàn Mỹ',23),
  ('gv_pham_van_tuan','Phạm Văn Tuấn',23),
  ('gv_nguyen_thi_luyen','Nguyễn Thị Luyến',23),
  ('gv_tang_thi_tu','Tăng Thị Tú',23),
  ('gv_vo_thi_van_anh','Võ Thị Vân Anh',23),
  ('gv_nguyen_khanh_linh','Nguyễn Khánh Linh',23),
  ('gv_phan_thi_huong','Phan Thị Hương',23),
  ('gv_nguyen_thi_kim_oanh','Nguyễn Thị Kim Oanh',23),
  ('gv_hoang_thi_mai','Hoàng Thị Mai',23),
  ('gv_tran_thanh_chung','Trần Thanh Chung',23),
  ('gv_nguyen_thi_hoa_ht','Nguyễn Thị Hòa HT',23),
  ('gv_phan_thi_thuong','Phan Thị Thương',23)
) as v(ma_gv, ho_ten, dinh_muc)
join truong t on t.ma_truong = 'THDL'
on conflict (truong_id, ma_gv) do nothing;

-- ---------- 4. Lớp, kèm giáo viên chủ nhiệm ----------
insert into lop (truong_id, diem_truong_id, ten, khoi, gvcn_id)
select t.id, d.id, v.ten, v.khoi::smallint, g.id
from (values
  ('1A',1,'gv_nguyen_thi_trinh'),
  ('1B',1,'gv_cao_thi_minh_khue'),
  ('1C',1,'gv_bui_thi_dung'),
  ('1D',1,'gv_hoang_thi_linh'),
  ('1E',1,'gv_dang_thi_hue'),
  ('2A',2,'gv_nguyen_thi_khanh'),
  ('2B',2,'gv_cao_thi_hoe'),
  ('2C',2,'gv_truong_thi_phuong'),
  ('2D',2,'gv_nguyen_thi_thoa'),
  ('2E',2,'gv_nguyen_thi_tram'),
  ('3A',3,'gv_dang_thi_dung'),
  ('3B',3,'gv_ho_thi_hang'),
  ('3C',3,'gv_chu_thi_tham'),
  ('3D',3,'gv_nguyen_thi_lam'),
  ('3E',3,'gv_tang_thi_huong_giang'),
  ('4A',4,'gv_nguyen_thi_oanh'),
  ('4B',4,'gv_phan_thi_bien'),
  ('4C',4,'gv_nguyen_thi_hong_thuy'),
  ('4D',4,'gv_nguyen_thi_thuy'),
  ('4E',4,'gv_nguyen_thi_hoa'),
  ('5A',5,'gv_bui_duc_hong'),
  ('5B',5,'gv_truong_thi_hong_ngoc'),
  ('5C',5,'gv_cao_thi_thanh_huong'),
  ('5D',5,'gv_nguyen_thi_hoan_my'),
  ('5E',5,'gv_pham_van_tuan')
) as v(ten, khoi, ma_gvcn)
join truong t on t.ma_truong = 'THDL'
join diem_truong d on d.truong_id = t.id and d.ten = 'Điểm trường Diễn Liên'
left join giao_vien g on g.truong_id = t.id and g.ma_gv = v.ma_gvcn
on conflict (truong_id, ten) do nothing;

-- ---------- 5. Bảng phân công giảng dạy ----------
insert into phan_cong (truong_id, giao_vien_id, lop_id, mon, so_tiet)
select t.id, g.id, l.id, v.mon, v.so_tiet::smallint
from (values
  ('gv_vo_thi_van_anh','1C','Tiếng Anh',2),
  ('gv_vo_thi_van_anh','1D','Tiếng Anh',2),
  ('gv_vo_thi_van_anh','1E','Tiếng Anh',2),
  ('gv_vo_thi_van_anh','2A','Tiếng Anh',2),
  ('gv_vo_thi_van_anh','2B','Tiếng Anh',2),
  ('gv_vo_thi_van_anh','2C','Tiếng Anh',2),
  ('gv_vo_thi_van_anh','2D','Tiếng Anh',2),
  ('gv_vo_thi_van_anh','2E','Tiếng Anh',2),
  ('gv_phan_thi_bien','4B','GDTC',2),
  ('gv_phan_thi_bien','4B','HDTN',3),
  ('gv_phan_thi_bien','4B','Khoa học',2),
  ('gv_phan_thi_bien','4B','LS&ĐL',2),
  ('gv_phan_thi_bien','4B','Tiếng Việt',7),
  ('gv_phan_thi_bien','4B','Toán',5),
  ('gv_phan_thi_bien','4B','Âm nhạc',1),
  ('gv_dang_thi_dung','3A','CN',1),
  ('gv_dang_thi_dung','3A','GDTC',2),
  ('gv_dang_thi_dung','3A','HDTN',3),
  ('gv_dang_thi_dung','3A','TNXH',2),
  ('gv_dang_thi_dung','3A','Tiếng Việt',7),
  ('gv_dang_thi_dung','3A','Toán',5),
  ('gv_dang_thi_dung','3A','Âm nhạc',1),
  ('gv_bui_thi_dung','1C','GDTC',2),
  ('gv_bui_thi_dung','1C','HDTN',3),
  ('gv_bui_thi_dung','1C','TNXH',2),
  ('gv_bui_thi_dung','1C','Tiếng Việt',12),
  ('gv_bui_thi_dung','1C','Toán',3),
  ('gv_tang_thi_huong_giang','3E','CN',1),
  ('gv_tang_thi_huong_giang','3E','GDTC',2),
  ('gv_tang_thi_huong_giang','3E','HDTN',3),
  ('gv_tang_thi_huong_giang','3E','TNXH',2),
  ('gv_tang_thi_huong_giang','3E','Tiếng Việt',7),
  ('gv_tang_thi_huong_giang','3E','Toán',5),
  ('gv_tang_thi_huong_giang','3E','Âm nhạc',1),
  ('gv_dang_thi_hue','1E','GDTC',2),
  ('gv_dang_thi_hue','1E','HDTN',3),
  ('gv_dang_thi_hue','1E','TNXH',2),
  ('gv_dang_thi_hue','1E','Tiếng Việt',12),
  ('gv_dang_thi_hue','1E','Toán',3),
  ('gv_nguyen_thi_hoa','4E','GDTC',2),
  ('gv_nguyen_thi_hoa','4E','HDTN',3),
  ('gv_nguyen_thi_hoa','4E','Khoa học',2),
  ('gv_nguyen_thi_hoa','4E','LS&ĐL',2),
  ('gv_nguyen_thi_hoa','4E','Tiếng Việt',7),
  ('gv_nguyen_thi_hoa','4E','Toán',5),
  ('gv_nguyen_thi_hoa_ht','2A','Đạo Đức',1),
  ('gv_nguyen_thi_hoa_ht','2B','Đạo Đức',1),
  ('gv_cao_thi_hoe','2B','GDTC',2),
  ('gv_cao_thi_hoe','2B','HDTN',3),
  ('gv_cao_thi_hoe','2B','TNXH',2),
  ('gv_cao_thi_hoe','2B','Tiếng Việt',10),
  ('gv_cao_thi_hoe','2B','Toán',5),
  ('gv_cao_thi_thanh_huong','5C','GDTC',2),
  ('gv_cao_thi_thanh_huong','5C','HDTN',3),
  ('gv_cao_thi_thanh_huong','5C','Khoa học',2),
  ('gv_cao_thi_thanh_huong','5C','LS&ĐL',2),
  ('gv_cao_thi_thanh_huong','5C','Tiếng Việt',7),
  ('gv_cao_thi_thanh_huong','5C','Toán',5),
  ('gv_ho_thi_hang','3B','CN',1),
  ('gv_ho_thi_hang','3B','GDTC',2),
  ('gv_ho_thi_hang','3B','HDTN',3),
  ('gv_ho_thi_hang','3B','TNXH',2),
  ('gv_ho_thi_hang','3B','Tiếng Việt',7),
  ('gv_ho_thi_hang','3B','Toán',5),
  ('gv_ho_thi_hang','3B','Âm nhạc',1),
  ('gv_nguyen_thi_kim_oanh','1A','Âm nhạc',1),
  ('gv_nguyen_thi_kim_oanh','1B','Âm nhạc',1),
  ('gv_nguyen_thi_kim_oanh','1C','Âm nhạc',1),
  ('gv_nguyen_thi_kim_oanh','1D','Âm nhạc',1),
  ('gv_nguyen_thi_kim_oanh','1E','Âm nhạc',1),
  ('gv_nguyen_thi_kim_oanh','2A','Âm nhạc',1),
  ('gv_nguyen_thi_kim_oanh','2B','Âm nhạc',1),
  ('gv_nguyen_thi_kim_oanh','2C','Âm nhạc',1),
  ('gv_nguyen_thi_kim_oanh','2D','Âm nhạc',1),
  ('gv_nguyen_thi_kim_oanh','2E','Âm nhạc',1),
  ('gv_cao_thi_minh_khue','1B','GDTC',2),
  ('gv_cao_thi_minh_khue','1B','HDTN',3),
  ('gv_cao_thi_minh_khue','1B','TNXH',2),
  ('gv_cao_thi_minh_khue','1B','Tiếng Việt',12),
  ('gv_cao_thi_minh_khue','1B','Toán',3),
  ('gv_nguyen_thi_khanh','2A','GDTC',2),
  ('gv_nguyen_thi_khanh','2A','HDTN',3),
  ('gv_nguyen_thi_khanh','2A','TNXH',2),
  ('gv_nguyen_thi_khanh','2A','Tiếng Việt',10),
  ('gv_nguyen_thi_khanh','2A','Toán',5),
  ('gv_nguyen_thi_lam','3D','CN',1),
  ('gv_nguyen_thi_lam','3D','GDTC',2),
  ('gv_nguyen_thi_lam','3D','HDTN',3),
  ('gv_nguyen_thi_lam','3D','TNXH',2),
  ('gv_nguyen_thi_lam','3D','Tiếng Việt',7),
  ('gv_nguyen_thi_lam','3D','Toán',5),
  ('gv_nguyen_thi_lam','3D','Âm nhạc',1),
  ('gv_hoang_thi_linh','1D','GDTC',2),
  ('gv_hoang_thi_linh','1D','HDTN',3),
  ('gv_hoang_thi_linh','1D','TNXH',2),
  ('gv_hoang_thi_linh','1D','Tiếng Việt',12),
  ('gv_hoang_thi_linh','1D','Toán',3),
  ('gv_nguyen_khanh_linh','1A','Tiếng Anh',2),
  ('gv_nguyen_khanh_linh','1B','Tiếng Anh',2),
  ('gv_nguyen_khanh_linh','3C','Tiếng Anh',4),
  ('gv_nguyen_khanh_linh','3D','Tiếng Anh',4),
  ('gv_nguyen_khanh_linh','3E','Tiếng Anh',4),
  ('gv_nguyen_thi_luyen','3A','Tiếng Anh',4),
  ('gv_nguyen_thi_luyen','4C','Tiếng Anh',4),
  ('gv_nguyen_thi_luyen','4D','Tiếng Anh',4),
  ('gv_nguyen_thi_luyen','5B','Tiếng Anh',4),
  ('gv_nguyen_thi_luyen','5C','Tiếng Anh',4),
  ('gv_nguyen_thi_luyen','5E','Tiếng Anh',4),
  ('gv_hoang_thi_mai','3A','Tin học',1),
  ('gv_hoang_thi_mai','3B','Tin học',1),
  ('gv_hoang_thi_mai','3C','Tin học',1),
  ('gv_hoang_thi_mai','3D','Tin học',1),
  ('gv_hoang_thi_mai','3E','Tin học',1),
  ('gv_hoang_thi_mai','4A','CN',1),
  ('gv_hoang_thi_mai','4A','Tin học',1),
  ('gv_hoang_thi_mai','4B','CN',1),
  ('gv_hoang_thi_mai','4B','Tin học',1),
  ('gv_hoang_thi_mai','4C','CN',1),
  ('gv_hoang_thi_mai','4C','Tin học',1),
  ('gv_hoang_thi_mai','4D','CN',1),
  ('gv_hoang_thi_mai','4D','Tin học',1),
  ('gv_hoang_thi_mai','4E','CN',1),
  ('gv_hoang_thi_mai','4E','Tin học',1),
  ('gv_hoang_thi_mai','5A','CN',1),
  ('gv_hoang_thi_mai','5A','Tin học',1),
  ('gv_hoang_thi_mai','5B','Tin học',1),
  ('gv_hoang_thi_mai','5C','CN',1),
  ('gv_hoang_thi_mai','5C','Tin học',1),
  ('gv_hoang_thi_mai','5D','Tin học',1),
  ('gv_hoang_thi_mai','5E','CN',1),
  ('gv_hoang_thi_mai','5E','Tin học',1),
  ('gv_nguyen_thi_hoan_my','5D','GDTC',2),
  ('gv_nguyen_thi_hoan_my','5D','HDTN',3),
  ('gv_nguyen_thi_hoan_my','5D','Khoa học',2),
  ('gv_nguyen_thi_hoan_my','5D','LS&ĐL',2),
  ('gv_nguyen_thi_hoan_my','5D','Tiếng Việt',7),
  ('gv_nguyen_thi_hoan_my','5D','Toán',5),
  ('gv_nguyen_thi_hoan_my','5D','Âm nhạc',1),
  ('gv_truong_thi_hong_ngoc','5B','GDTC',2),
  ('gv_truong_thi_hong_ngoc','5B','HDTN',3),
  ('gv_truong_thi_hong_ngoc','5B','Khoa học',2),
  ('gv_truong_thi_hong_ngoc','5B','LS&ĐL',2),
  ('gv_truong_thi_hong_ngoc','5B','Tiếng Việt',7),
  ('gv_truong_thi_hong_ngoc','5B','Toán',5),
  ('gv_truong_thi_hong_ngoc','5B','Âm nhạc',1),
  ('gv_nguyen_thi_oanh','4A','GDTC',2),
  ('gv_nguyen_thi_oanh','4A','HDTN',3),
  ('gv_nguyen_thi_oanh','4A','Khoa học',2),
  ('gv_nguyen_thi_oanh','4A','LS&ĐL',2),
  ('gv_nguyen_thi_oanh','4A','Tiếng Việt',7),
  ('gv_nguyen_thi_oanh','4A','Toán',5),
  ('gv_nguyen_thi_oanh','4A','Âm nhạc',1),
  ('gv_phan_thi_huong','1A','Mỹ thuật',1),
  ('gv_phan_thi_huong','1B','Mỹ thuật',1),
  ('gv_phan_thi_huong','1C','Mỹ thuật',1),
  ('gv_phan_thi_huong','1D','Mỹ thuật',1),
  ('gv_phan_thi_huong','1E','Mỹ thuật',1),
  ('gv_phan_thi_huong','2A','Mỹ thuật',1),
  ('gv_phan_thi_huong','2B','Mỹ thuật',1),
  ('gv_phan_thi_huong','2C','Mỹ thuật',1),
  ('gv_phan_thi_huong','2D','Mỹ thuật',1),
  ('gv_phan_thi_huong','2E','Mỹ thuật',1),
  ('gv_phan_thi_huong','3A','Mỹ thuật',1),
  ('gv_phan_thi_huong','3B','Mỹ thuật',1),
  ('gv_phan_thi_huong','3C','Mỹ thuật',1),
  ('gv_phan_thi_huong','3D','Mỹ thuật',1),
  ('gv_phan_thi_huong','3E','Mỹ thuật',1),
  ('gv_phan_thi_huong','4A','Mỹ thuật',1),
  ('gv_phan_thi_huong','4B','Mỹ thuật',1),
  ('gv_phan_thi_huong','4C','Mỹ thuật',1),
  ('gv_phan_thi_huong','4D','Mỹ thuật',1),
  ('gv_phan_thi_huong','4E','Mỹ thuật',1),
  ('gv_phan_thi_huong','5A','Mỹ thuật',1),
  ('gv_phan_thi_huong','5B','Mỹ thuật',1),
  ('gv_phan_thi_huong','5C','Mỹ thuật',1),
  ('gv_phan_thi_huong','5D','Mỹ thuật',1),
  ('gv_phan_thi_huong','5E','Mỹ thuật',1),
  ('gv_truong_thi_phuong','2C','GDTC',2),
  ('gv_truong_thi_phuong','2C','HDTN',3),
  ('gv_truong_thi_phuong','2C','TNXH',2),
  ('gv_truong_thi_phuong','2C','Tiếng Việt',10),
  ('gv_truong_thi_phuong','2C','Toán',5),
  ('gv_nguyen_thi_thoa','2D','GDTC',2),
  ('gv_nguyen_thi_thoa','2D','HDTN',3),
  ('gv_nguyen_thi_thoa','2D','TNXH',2),
  ('gv_nguyen_thi_thoa','2D','Tiếng Việt',10),
  ('gv_nguyen_thi_thoa','2D','Toán',5),
  ('gv_nguyen_thi_thuy','4D','GDTC',2),
  ('gv_nguyen_thi_thuy','4D','HDTN',3),
  ('gv_nguyen_thi_thuy','4D','Khoa học',2),
  ('gv_nguyen_thi_thuy','4D','LS&ĐL',2),
  ('gv_nguyen_thi_thuy','4D','Tiếng Việt',7),
  ('gv_nguyen_thi_thuy','4D','Toán',5),
  ('gv_nguyen_thi_thuy','4D','Âm nhạc',1),
  ('gv_phan_thi_thuong','1A','Đạo Đức',1),
  ('gv_phan_thi_thuong','1B','Đạo Đức',1),
  ('gv_phan_thi_thuong','1C','Đạo Đức',1),
  ('gv_phan_thi_thuong','1D','Đạo Đức',1),
  ('gv_phan_thi_thuong','1E','Đạo Đức',1),
  ('gv_phan_thi_thuong','2C','Đạo Đức',1),
  ('gv_phan_thi_thuong','2D','Đạo Đức',1),
  ('gv_phan_thi_thuong','2E','Đạo Đức',1),
  ('gv_phan_thi_thuong','3A','Đạo Đức',1),
  ('gv_phan_thi_thuong','3B','Đạo Đức',1),
  ('gv_phan_thi_thuong','3C','Đạo Đức',1),
  ('gv_phan_thi_thuong','3D','Đạo Đức',1),
  ('gv_phan_thi_thuong','3E','Đạo Đức',1),
  ('gv_phan_thi_thuong','4A','Đạo Đức',1),
  ('gv_phan_thi_thuong','4B','Đạo Đức',1),
  ('gv_phan_thi_thuong','4C','Đạo Đức',1),
  ('gv_phan_thi_thuong','4D','Đạo Đức',1),
  ('gv_phan_thi_thuong','4E','Đạo Đức',1),
  ('gv_phan_thi_thuong','5A','Đạo Đức',1),
  ('gv_phan_thi_thuong','5B','Đạo Đức',1),
  ('gv_phan_thi_thuong','5C','Đạo Đức',1),
  ('gv_phan_thi_thuong','5D','Đạo Đức',1),
  ('gv_phan_thi_thuong','5E','Đạo Đức',1),
  ('gv_chu_thi_tham','3C','CN',1),
  ('gv_chu_thi_tham','3C','GDTC',2),
  ('gv_chu_thi_tham','3C','HDTN',3),
  ('gv_chu_thi_tham','3C','TNXH',2),
  ('gv_chu_thi_tham','3C','Tiếng Việt',7),
  ('gv_chu_thi_tham','3C','Toán',5),
  ('gv_chu_thi_tham','3C','Âm nhạc',1),
  ('gv_nguyen_thi_hong_thuy','4C','GDTC',2),
  ('gv_nguyen_thi_hong_thuy','4C','HDTN',3),
  ('gv_nguyen_thi_hong_thuy','4C','Khoa học',2),
  ('gv_nguyen_thi_hong_thuy','4C','LS&ĐL',2),
  ('gv_nguyen_thi_hong_thuy','4C','Tiếng Việt',7),
  ('gv_nguyen_thi_hong_thuy','4C','Toán',5),
  ('gv_nguyen_thi_hong_thuy','4C','Âm nhạc',1),
  ('gv_nguyen_thi_trinh','1A','GDTC',2),
  ('gv_nguyen_thi_trinh','1A','HDTN',3),
  ('gv_nguyen_thi_trinh','1A','TNXH',2),
  ('gv_nguyen_thi_trinh','1A','Tiếng Việt',12),
  ('gv_nguyen_thi_trinh','1A','Toán',3),
  ('gv_nguyen_thi_tram','2E','GDTC',2),
  ('gv_nguyen_thi_tram','2E','HDTN',3),
  ('gv_nguyen_thi_tram','2E','TNXH',2),
  ('gv_nguyen_thi_tram','2E','Tiếng Việt',10),
  ('gv_nguyen_thi_tram','2E','Toán',5),
  ('gv_tang_thi_tu','3B','Tiếng Anh',4),
  ('gv_tang_thi_tu','4A','Tiếng Anh',4),
  ('gv_tang_thi_tu','4B','Tiếng Anh',4),
  ('gv_tang_thi_tu','4E','Tiếng Anh',4),
  ('gv_tang_thi_tu','5A','Tiếng Anh',4),
  ('gv_tang_thi_tu','5D','Tiếng Anh',4),
  ('gv_tran_thanh_chung','4E','Âm nhạc',1),
  ('gv_tran_thanh_chung','5B','CN',1),
  ('gv_tran_thanh_chung','5C','Âm nhạc',1),
  ('gv_tran_thanh_chung','5D','CN',1),
  ('gv_bui_duc_hong','5A','GDTC',2),
  ('gv_bui_duc_hong','5A','HDTN',3),
  ('gv_bui_duc_hong','5A','Khoa học',2),
  ('gv_bui_duc_hong','5A','LS&ĐL',2),
  ('gv_bui_duc_hong','5A','Tiếng Việt',7),
  ('gv_bui_duc_hong','5A','Toán',5),
  ('gv_bui_duc_hong','5A','Âm nhạc',1),
  ('gv_pham_van_tuan','5E','GDTC',2),
  ('gv_pham_van_tuan','5E','HDTN',3),
  ('gv_pham_van_tuan','5E','Khoa học',2),
  ('gv_pham_van_tuan','5E','LS&ĐL',2),
  ('gv_pham_van_tuan','5E','Tiếng Việt',7),
  ('gv_pham_van_tuan','5E','Toán',5),
  ('gv_pham_van_tuan','5E','Âm nhạc',1)
) as v(ma_gv, ten_lop, mon, so_tiet)
join truong t on t.ma_truong = 'THDL'
join giao_vien g on g.truong_id = t.id and g.ma_gv = v.ma_gv
join lop l on l.truong_id = t.id and l.ten = v.ten_lop
on conflict (truong_id, giao_vien_id, lop_id, mon) do nothing;

-- ---------- 6. Kiểm tra ----------
-- Bảy cột đầu phải ra: 1 · 8 · 35 · 25 · 25 · 265 · 710
select
  (select count(*) from diem_truong d where d.truong_id = t.id)              as diem_truong,
  (select count(*) from khung_gio k where k.truong_id = t.id and k.bat)      as buoi_hoc,
  (select count(*) from giao_vien g where g.truong_id = t.id)                as giao_vien,
  (select count(*) from lop l where l.truong_id = t.id)                      as lop,
  (select count(*) from lop l where l.truong_id = t.id and l.gvcn_id is not null) as lop_co_chu_nhiem,
  (select count(*) from phan_cong p where p.truong_id = t.id)                as dong_phan_cong,
  (select coalesce(sum(p.so_tiet),0) from phan_cong p where p.truong_id = t.id) as tong_tiet
from truong t where t.ma_truong = 'THDL';

-- ---------- 7. Kiểm tra khung giờ theo khối ----------
-- Cộng số tiết mỗi khối trong các buổi đang bật.
-- Phải ra đúng chuẩn CT GDPT 2018:  27 · 27 · 28 · 30 · 30
select
  sum((k.so_tiet_khoi->>'1')::int) as khoi_1,
  sum((k.so_tiet_khoi->>'2')::int) as khoi_2,
  sum((k.so_tiet_khoi->>'3')::int) as khoi_3,
  sum((k.so_tiet_khoi->>'4')::int) as khoi_4,
  sum((k.so_tiet_khoi->>'5')::int) as khoi_5
from khung_gio k
join truong t on t.id = k.truong_id and t.ma_truong = 'THDL'
where k.bat;
